/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TrackRouteImport } from './routes/track'
import { Route as ReportRouteImport } from './routes/report'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackIdRouteImport } from './routes/track.$id'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackIdRoute = TrackIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TrackRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/onboard': typeof OnboardRoute
  '/report': typeof ReportRoute
  '/track': typeof TrackRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/track/$id': typeof TrackIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/onboard': typeof OnboardRoute
  '/report': typeof ReportRoute
  '/track': typeof TrackRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/track/$id': typeof TrackIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/onboard': typeof OnboardRoute
  '/report': typeof ReportRoute
  '/track': typeof TrackRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/track/$id': typeof TrackIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/onboard'
    | '/report'
    | '/track'
    | '/welcome'
    | '/track/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/onboard'
    | '/report'
    | '/track'
    | '/welcome'
    | '/track/$id'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/onboard'
    | '/report'
    | '/track'
    | '/welcome'
    | '/track/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  OnboardRoute: typeof OnboardRoute
  ReportRoute: typeof ReportRoute
  TrackRoute: typeof TrackRouteWithChildren
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$id': {
      id: '/track/$id'
      path: '/$id'
      fullPath: '/track/$id'
      preLoaderRoute: typeof TrackIdRouteImport
      parentRoute: typeof TrackRoute
    }
  }
}

interface TrackRouteChildren {
  TrackIdRoute: typeof TrackIdRoute
}

const TrackRouteChildren: TrackRouteChildren = {
  TrackIdRoute: TrackIdRoute,
}

const TrackRouteWithChildren = TrackRoute._addFileChildren(TrackRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  OnboardRoute: OnboardRoute,
  ReportRoute: ReportRoute,
  TrackRoute: TrackRouteWithChildren,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
